require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '15.5'

target 'PlantApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  



  target 'PlantAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end